// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function toString(buffer) {
  return buffer.toString();
}

var partial_arg = Buffer;

function alloc(param) {
  return partial_arg.alloc(param);
}

var partial_arg$1 = Buffer;

function concat(param) {
  return partial_arg$1.concat(param);
}

function from(encoding, data) {
  return Buffer.from(data, Js_null_undefined.fromOption(encoding));
}

var get = function (buf,idx){return buf[idx];};

var set = function (buf,idx,el){buf[idx] = el;};

exports.alloc = alloc;
exports.concat = concat;
exports.from = from;
exports.toString = toString;
exports.get = get;
exports.set = set;
/* partial_arg Not a pure module */
