// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Os = require("os");

function hostname() {
  return Os.hostname();
}

function platform() {
  return Os.platform();
}

exports.hostname = hostname;
exports.platform = platform;
/* os Not a pure module */
