// Generated by BUCKLESCRIPT VERSION 3.1.1, PLEASE EDIT WITH CARE
'use strict';

var Os = require("os");

function cpus() {
  return Os.cpus();
}

function hostname() {
  return Os.hostname();
}

function platform() {
  return Os.platform();
}

exports.cpus = cpus;
exports.hostname = hostname;
exports.platform = platform;
/* os Not a pure module */
