// Generated by BUCKLESCRIPT VERSION 3.1.1, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");

function dirname(prim) {
  return Path.dirname(prim);
}

function normalize(prim) {
  return Path.normalize(prim);
}

exports.dirname = dirname;
exports.normalize = normalize;
/* path Not a pure module */
