// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';


function string_of_signal(param) {
  if (param >= -419144110) {
    if (param >= -418600653) {
      if (param >= 313061648) {
        if (param >= 1052815119) {
          return "SIGKILL";
        } else {
          return "SIGWINCH";
        }
      } else if (param >= 19585038) {
        return "SIGBREAK";
      } else {
        return "SIGSEV";
      }
    } else if (param >= -419095938) {
      return "SIGINT";
    } else {
      return "SIGHUP";
    }
  } else if (param >= -995060003) {
    if (param >= -419442481) {
      if (param >= -419244694) {
        return "SIGFPE";
      } else {
        return "SIGBUS";
      }
    } else if (param >= -983274258) {
      return "SIGUSR1";
    } else {
      return "SIGTERM";
    }
  } else if (param >= -1005404301) {
    return "SIGSTOP";
  } else {
    return "SIGPIPE";
  }
}

function on(signal, fn) {
  process.on(string_of_signal(signal), fn);
  return /* () */0;
}

exports.on = on;
/* No side effect */
