// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Child_process = require("child_process");
var Buffer$LidcoreBsNode = require("./buffer.js");

function exec(cmd, cb) {
  Child_process.exec(cmd, (function (err, stdout, stderr) {
          return cb(err, /* tuple */[
                      stdout,
                      stderr
                    ]);
        }));
  return /* () */0;
}

function execSync(cmd) {
  return Buffer$LidcoreBsNode.toString(Child_process.execSync(cmd));
}

exports.exec = exec;
exports.execSync = execSync;
/* child_process Not a pure module */
