// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Child_process = require("child_process");
var Buffer$LidcoreBsNode = require("./buffer.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function stdioConfig(param) {
  if (typeof param === "number") {
    if (param >= 892411982) {
      return "pipe";
    } else {
      return "ignore";
    }
  } else {
    return param[1];
  }
}

function stdioConfig$1(param) {
  return /* array */[
          stdioConfig(param[/* stdin */0]),
          stdioConfig(param[/* stdout */1]),
          stdioConfig(param[/* stderr */2])
        ];
}

function exec(cmd, cb) {
  Child_process.exec(cmd, (function (err, stdout, stderr) {
          return cb(err, /* tuple */[
                      stdout,
                      stderr
                    ]);
        }));
  return /* () */0;
}

function execSync(cmd) {
  return Buffer$LidcoreBsNode.toString(undefined, undefined, undefined, Child_process.execSync(cmd));
}

function execFile(cwd, env, encoding, timeout, maxBuffer, killSignal, uid, gid, windowsHide, windowsVerbatimOptions, shell, cmd, args, cb) {
  var tmp = { };
  if (cwd !== undefined) {
    tmp.cwd = Js_primitive.valFromOption(cwd);
  }
  if (env !== undefined) {
    tmp.env = Js_primitive.valFromOption(env);
  }
  if (encoding !== undefined) {
    tmp.encoding = Js_primitive.valFromOption(encoding);
  }
  if (timeout !== undefined) {
    tmp.timeout = Js_primitive.valFromOption(timeout);
  }
  if (maxBuffer !== undefined) {
    tmp.maxBuffer = Js_primitive.valFromOption(maxBuffer);
  }
  if (killSignal !== undefined) {
    tmp.killSignal = Js_primitive.valFromOption(killSignal);
  }
  if (uid !== undefined) {
    tmp.uid = Js_primitive.valFromOption(uid);
  }
  if (gid !== undefined) {
    tmp.gid = Js_primitive.valFromOption(gid);
  }
  if (windowsHide !== undefined) {
    tmp.windowsHide = Js_primitive.valFromOption(windowsHide);
  }
  if (windowsVerbatimOptions !== undefined) {
    tmp.windowsVerbatimOptions = Js_primitive.valFromOption(windowsVerbatimOptions);
  }
  if (shell !== undefined) {
    tmp.shell = Js_primitive.valFromOption(shell);
  }
  var options = tmp;
  Child_process.execFile(cmd, args, options, (function (err, stdout, stderr) {
          return cb(err, /* tuple */[
                      stdout,
                      stderr
                    ]);
        }));
  return /* () */0;
}

function spawn(cwd, env, stdio, shell, cmd) {
  var stdio$1 = stdio !== undefined ? stdioConfig$1(stdio) : undefined;
  var tmp = { };
  if (cwd !== undefined) {
    tmp.cwd = Js_primitive.valFromOption(cwd);
  }
  if (env !== undefined) {
    tmp.env = Js_primitive.valFromOption(env);
  }
  if (stdio$1 !== undefined) {
    tmp.stdio = Js_primitive.valFromOption(stdio$1);
  }
  if (shell !== undefined) {
    tmp.shell = Js_primitive.valFromOption(shell);
  }
  var options = tmp;
  return Child_process.spawn(cmd, options);
}

function on(p, param) {
  if (param[0] >= 771171134) {
    var fn = param[1];
    p.on("exit", (function (code, signal) {
            if (code == null) {
              if (signal == null) {
                throw [
                      Caml_builtin_exceptions.assert_failure,
                      /* tuple */[
                        "child_process.ml",
                        107,
                        17
                      ]
                    ];
              } else {
                return Curry._1(fn, /* `Signal */[
                            -384130424,
                            signal
                          ]);
              }
            } else if (signal == null) {
              return Curry._1(fn, /* `Code */[
                          748543309,
                          code
                        ]);
            } else {
              throw [
                    Caml_builtin_exceptions.assert_failure,
                    /* tuple */[
                      "child_process.ml",
                      107,
                      17
                    ]
                  ];
            }
          }));
    return /* () */0;
  } else {
    var fn$1 = param[1];
    p.on("error", Curry.__1(fn$1));
    return /* () */0;
  }
}

function stdin(prim) {
  return prim.stdin;
}

function stdout(prim) {
  return prim.stdout;
}

function stderr(prim) {
  return prim.stderr;
}

exports.exec = exec;
exports.execSync = execSync;
exports.execFile = execFile;
exports.spawn = spawn;
exports.on = on;
exports.stdin = stdin;
exports.stdout = stdout;
exports.stderr = stderr;
/* child_process Not a pure module */
