// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Crypto = require("crypto");

function createHash(prim) {
  return Crypto.createHash(prim);
}

function update(prim, prim$1) {
  prim.update(prim$1);
  return /* () */0;
}

function digest(prim, prim$1) {
  return prim.digest(prim$1);
}

exports.createHash = createHash;
exports.update = update;
exports.digest = digest;
/* crypto Not a pure module */
