// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Curry = require("bs-platform/lib/js/curry.js");
var BsCallback = require("bs-callback/src/bsCallback.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var Buffer$LidcoreBsNode = require("./buffer.js");

function read(position, fd, buffer, offset, length, cb) {
  var position$1 = Js_null_undefined.fromOption(position);
  Fs.read(fd, buffer, offset, length, position$1, (function (err, read, buffer) {
          return cb(err, /* tuple */[
                      read,
                      buffer
                    ]);
        }));
  return /* () */0;
}

function write(position, encoding, fd, data, offset, length, cb) {
  var position$1 = Js_null_undefined.fromOption(position);
  var encoding$1 = Js_null_undefined.fromOption(encoding);
  Fs.write(fd, data, offset, length, position$1, encoding$1, (function (err, written, str) {
          return cb(err, /* tuple */[
                      written,
                      str
                    ]);
        }));
  return /* () */0;
}

function createStream(fn, path, fd, autoClose, _) {
  var tmp = { };
  if (fd) {
    tmp.fd = fd[0];
  }
  if (autoClose) {
    tmp.autoClose = autoClose[0];
  }
  var params = tmp;
  var $$default = function (param) {
    if (param) {
      return param[0];
    } else {
      return null;
    }
  };
  var path$1 = $$default(path);
  return Curry._2(fn, path$1, params);
}

function createReadStream(param, param$1, param$2, param$3) {
  return createStream((function (prim, prim$1) {
                return Fs.createReadStream(prim, prim$1);
              }), param, param$1, param$2, param$3);
}

function createWriteStream(param, param$1, param$2, param$3) {
  return createStream((function (prim, prim$1) {
                return Fs.createWriteStream(prim, prim$1);
              }), param, param$1, param$2, param$3);
}

function readFile(path) {
  return (function (param) {
      return BsCallback.$great$great((function (param) {
                    Fs.readFile(path, param);
                    return /* () */0;
                  }), (function (data) {
                    var partial_arg = Buffer$LidcoreBsNode.toString(data);
                    return (function (param) {
                        return BsCallback.$$return(partial_arg, param);
                      });
                  }), param);
    });
}

function readFileSync(path) {
  return Buffer$LidcoreBsNode.toString(Fs.readFileSync(path));
}

function copyFileSync(prim, prim$1) {
  Fs.copyFileSync(prim, prim$1);
  return /* () */0;
}

function existsSync(prim) {
  return Fs.existsSync(prim);
}

function openFile(prim, prim$1, prim$2) {
  Fs.open(prim, prim$1, prim$2);
  return /* () */0;
}

function close(prim, prim$1) {
  Fs.close(prim, prim$1);
  return /* () */0;
}

function unlinkSync(prim) {
  Fs.unlinkSync(prim);
  return /* () */0;
}

function writeFile(prim, prim$1, prim$2) {
  Fs.writeFile(prim, prim$1, prim$2);
  return /* () */0;
}

function rmdirSync(prim) {
  Fs.rmdirSync(prim);
  return /* () */0;
}

function statSync(prim) {
  return Fs.statSync(prim);
}

exports.copyFileSync = copyFileSync;
exports.createWriteStream = createWriteStream;
exports.createReadStream = createReadStream;
exports.existsSync = existsSync;
exports.openFile = openFile;
exports.close = close;
exports.unlinkSync = unlinkSync;
exports.read = read;
exports.readFile = readFile;
exports.readFileSync = readFileSync;
exports.write = write;
exports.writeFile = writeFile;
exports.rmdirSync = rmdirSync;
exports.statSync = statSync;
/* fs Not a pure module */
