// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");

function dirname(prim) {
  return Path.dirname(prim);
}

function extname(prim) {
  return Path.extname(prim);
}

function normalize(prim) {
  return Path.normalize(prim);
}

exports.dirname = dirname;
exports.extname = extname;
exports.normalize = normalize;
/* path Not a pure module */
