// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -1039219809,
    "SIGPIPE"
  ],
  /* tuple */[
    -1005404301,
    "SIGSTOP"
  ],
  /* tuple */[
    -995060003,
    "SIGTERM"
  ],
  /* tuple */[
    -983274258,
    "SIGUSR1"
  ],
  /* tuple */[
    -419442481,
    "SIGBUS"
  ],
  /* tuple */[
    -419244694,
    "SIGFPE"
  ],
  /* tuple */[
    -419144110,
    "SIGHUP"
  ],
  /* tuple */[
    -419095938,
    "SIGINT"
  ],
  /* tuple */[
    -418600653,
    "SIGSEV"
  ],
  /* tuple */[
    19585038,
    "SIGBREAK"
  ],
  /* tuple */[
    313061648,
    "SIGWINCH"
  ]
];

function on(signal, fn) {
  process.on(Js_mapperRt.binarySearch(11, signal, jsMapperConstantArray), fn);
  return /* () */0;
}

exports.on = on;
/* No side effect */
