// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function resolve(paths, name) {
  return require.resolve(name, Js_null_undefined.fromOption(paths));
}

var main = require.main;

exports.main = main;
exports.resolve = resolve;
/* main Not a pure module */
